#spring:
  #jsp
 # mvc:
   # view: 
   #   prefix: /WEB-INF/views/
   #   suffix: .jsp
    #static-path-pattern: /resources/**

spring:
  thymeleaf:
    prefix : classpath:templates/
    suffix : .html
    cache : false


 
  #jdbc 설정
  datasource:
    url: jdbc:mysql://localhost:3306/shop?autoReconnect=true
    username: root
    password: Sk696950@@
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  security:
    oauth2:
      client:
        registration:
          google:            
            client-id: 본인 google client-id
            client-secret: 본인 google client-secret

          facebook:            
            client-id: 본인 facebook client-id
            client-secret: 본인 facebook client-secret

custom: 
  oauth2: 
    kakao:
      client-id: 본인 kakao client-id
      client-secret: 본인 kakao client-secret
    naver:
      client-id: 본인 naver client-id
      client-secret: 본인 naver client-secret
      
mybatis:
  mapper-locations: mybatis-mapper/**/*.xml
  type-aliases-package: com.fpshop.model
    

#Tomcat Port
server: 
  port: 8090
